## PARA RODAR:
# bundle exec jekyll serve --livereload

url: https://vinyluis.github.io/viniciustrevisan.github.io
baseurl: /page

# Site settings
title: Vinícius Trevisan
title_complement: MSc in Deep Learning | Senior Data Scientist
# email: your-email@domain.com
description: "Vinicius Trevisan's portfolio website. I am an experienced data scientist, having worked in many data science and machine learning projects in finance and elevator maintenance industries. My focus area of academic study is use of deep learning for computer vision and image synthesis. I believe I have a strong sense of integration between business and data teams, allowing for data products to positively impact business results."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/vinicius-trevisan/
  - title: medium
    url: https://medium.com/@vinicius_trevisan
  - title: github
    url: https://github.com/vinyluis

# Build settings
markdown: kramdown
permalink: pretty

# ----- DEFAULT UNUSED SETTINGS

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #
